// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmgyjtwkvsmtzwmhllvq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhtZ3lqdHdrdnNtdHp3bWhsbHZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2NTgzMTAsImV4cCI6MjA2NzIzNDMxMH0.WhFMNbHS4ylwT8YSLzcBJoG28vCN80JfrFkBYGKZwq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});